TEST_DB_HOST='127.0.0.1'
TEST_DB_PORT='5433'
TEST_DB_USERNAME='my_user'
TEST_DB_PASSWORD='my_password'
TEST_DB_NAME='my_database'
GOMODULE='on'


APP_DB_HOST='127.0.0.1'
APP_DB_PORT='5432'
APP_DB_USERNAME='my_user'
APP_DB_PASSWORD='my_password'
APP_DB_NAME='my_database'


dev:
	APP_DB_HOST=$(APP_DB_HOST) APP_DB_PORT=$(APP_DB_PORT) APP_DB_USERNAME=$(APP_DB_USERNAME) APP_DB_PASSWORD=$(APP_DB_PASSWORD) APP_DB_NAME=$(APP_DB_NAME) GO111MODULE=$(GOMODULE) gin -p 8001 run main.go

test:
	TEST_DB_HOST=$(TEST_DB_HOST) TEST_DB_PORT=$(TEST_DB_PORT) TEST_DB_USERNAME=$(TEST_DB_USERNAME) TEST_DB_PASSWORD=$(TEST_DB_PASSWORD) TEST_DB_NAME=$(TEST_DB_NAME) GO111MODULE=$(GOMODULE) go test -v
	 
	
	  
	  
	
	